kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: san-bamboo-claim
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "managed-san-storage"
spec:
  storageClassName: managed-san-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
